language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rondeg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rondeg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  environmentname: "Dockerreact-env"
  bucketname: "elasticbeanstalk-eu-west-2-912288257149"
  bucketpath: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY