# Use an existing docker image as a base
FROM node:16-alpine

# Download and install a dependancy
WORKDIR /app
COPY ./package.json .
RUN npm install
COPY . .

# Tell the image what to do when it starts as a containers
CMD ["npm", "run", "start"]